/* ===== 泰国市集数据 · 各城市分页共享 ===== */

// 城市（每个城市 = 一个分页）
const THAI_CITIES = [
  { key:'bangkok',   cn:'曼谷', en:'Bangkok',    icon:'🛺', sub:'市集之都 · 夜市 / 水上市场 / 铁道市场',
    img:'https://images.unsplash.com/photo-1563492065599-3520f775eeed?w=1000&q=80' },
  { key:'chiangmai', cn:'清迈', en:'Chiang Mai', icon:'🏯', sub:'手作与步行街 · 古城里的文创夜市',
    img:'https://images.unsplash.com/photo-1512553353614-82a7370096dc?w=1000&q=80' },
  { key:'phuket',    cn:'普吉', en:'Phuket',     icon:'🏝️', sub:'中葡老城与海岛 · 南部市集',
    img:'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=1000&q=80' },
  { key:'huahin',    cn:'华欣', en:'Hua Hin',    icon:'🌅', sub:'海边的创意市集 · 文艺之夜',
    img:'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1000&q=80' },
  { key:'pattaya',   cn:'芭提雅', en:'Pattaya',  icon:'🌴', sub:'大型周末夜市与水上市场',
    img:'https://images.unsplash.com/photo-1581873372796-635b67ca2008?w=1000&q=80' },
  { key:'ayutthaya', cn:'大城', en:'Ayutthaya',  icon:'🏛️', sub:'古都水上市场 · 世遗古寺旁',
    img:'https://images.unsplash.com/photo-1528181304800-259b08848526?w=1000&q=80' },
];

// 市集类型中文名
const CAT_NAMES = {
  weekend:'周末市集', night:'夜市', floating:'水上市场', railway:'铁道市场',
  creative:'创意市集', walking:'步行街夜市', food:'美食街', indoor:'室内市集', local:'本地市场'
};

// 全部市集
const THAI_MARKETS = [
  // ===== 曼谷 BANGKOK =====
  { city:'bangkok', cat:'weekend', hi:true, name:'札都甲周末市集', en:'Chatuchak Weekend Market', state:'Bangkok',
    img:'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80',
    desc:'全球最大的周末市集，超 15,000 个摊位、27 个分区，从服饰、古董、家居到绿植、宠物无所不有，一天根本逛不完。',
    time:'周六日 09:00–18:00（部分批发档周三五也开）', ico:'🚇', transport:'BTS Mo Chit / MRT Kamphaeng Phet 站，出站即到',
    eat:'椰子冰淇淋、烤香蕉、Section 26 的船面', tip:'上午 9–11 点最凉快人少；记地标分区号防迷路' },
  { city:'bangkok', cat:'night', hi:true, name:'乔德夜市（Rama 9）', en:'Jodd Fairs', state:'Bangkok',
    img:'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&q=80',
    desc:'取代旧拉差达火车夜市的当红夜市，五彩棚顶俯拍超出片，美食、小酒馆、潮流摊一应俱全，年轻人最爱。',
    time:'每天约 16:00–24:00', ico:'🚇', transport:'MRT Phra Ram 9 站，步行 5 分钟',
    eat:'火山排骨 Leng Saap、海鲜叠叠乐', tip:'另有 DanNeramit 古堡分店，主打复古打卡' },
  { city:'bangkok', cat:'railway', hi:true, name:'美功铁道市场', en:'Maeklong Railway Market', state:'Samut Songkhram',
    img:'https://images.unsplash.com/photo-1597149481080-1f5c2b91f8a9?w=800&q=80',
    desc:'火车贴着菜摊缓缓驶过，摊主听到汽笛就秒收遮阳伞——“收伞市场”的奇观一天上演 8 次，看完火车伞再瞬间合拢。',
    time:'市场全天开；火车进出约 08:30 / 11:10 / 14:30 / 17:40', ico:'🚐', transport:'曼谷出发约 1.5h，多与丹嫩沙朵拼一日游',
    eat:'现烤海虾、椰糖小食、新鲜热带水果', tip:'提前 10 分钟站到铁轨边占机位，别太贴近' },
  { city:'bangkok', cat:'floating', hi:true, name:'丹嫩沙朵水上市场', en:'Damnoen Saduak Floating Market', state:'Ratchaburi',
    img:'https://images.unsplash.com/photo-1528181304800-259b08848526?w=800&q=80',
    desc:'泰国最经典的水上市场，明信片上戴斗笠划船卖水果的画面就出自这里。坐长尾船穿梭水道，画面感满分。',
    time:'每天 07:00–11:00，越早越热闹、人越少', ico:'🚐', transport:'曼谷西南约 100km，常与美功拼半日游',
    eat:'船上现煮船面、椰浆糕、芒果糯米饭', tip:'游客偏多，先讲好船费再上船，会还价' },
  { city:'bangkok', cat:'floating', hi:true, name:'安帕瓦水上市场', en:'Amphawa Floating Market', state:'Samut Songkhram',
    img:'https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=800&q=80',
    desc:'比丹嫩沙朵更本地、更悠闲的傍晚水上市场，运河两岸老木屋林立，傍晚还能坐船去看萤火虫闪烁。',
    time:'周五·六·日 12:00–20:00', ico:'🚐', transport:'曼谷出发约 1.5h，可住一晚河边民宿',
    eat:'船上炭烤海鲜、烤大虾、海鲜炒粉', tip:'日落后加坐萤火虫游船，雨季后最壮观' },
  { city:'bangkok', cat:'food', hi:true, name:'耀华力路唐人街', en:'Yaowarat Chinatown', state:'Bangkok',
    img:'https://images.unsplash.com/photo-1559667326-145c2c4e3a3c?w=800&q=80',
    desc:'入夜后整条街变身露天美食天堂，霓虹招牌下海鲜大排档、潮州糖水、烤生蚝热气腾腾，米其林街头摊也藏在巷里。',
    time:'傍晚 18:00 后最旺，周一较多档休息', ico:'🚇', transport:'MRT Wat Mangkon 站，1 号出口即唐人街',
    eat:'炭烤海鲜、鳄鱼河粉、T&K 海鲜、烤栗子', tip:'现金为主；空腹来，少量多摊扫街最划算' },
  { city:'bangkok', cat:'night', hi:false, name:'席娜卡琳火车夜市', en:'Talad Rot Fai Srinakarin', state:'Bangkok',
    img:'https://images.unsplash.com/photo-1581873372796-635b67ca2008?w=800&q=80',
    desc:'主打复古风的大型夜市，老爷车、古董杂货、霓虹酒吧一应俱全，二楼天台俯拍五彩铁皮屋顶是经典机位。',
    time:'周四–周日 17:00–24:00', ico:'🚐', transport:'位置偏东，建议打车/Grab 前往',
    eat:'泰式烤肉串、复古酒吧调酒、海鲜锅', tip:'vintage 控天堂，淘古着、旧相机来这准没错' },
  { city:'bangkok', cat:'indoor', hi:false, name:'ICONSIAM·SOOK Siam', en:'河滨天地室内市集', state:'Bangkok',
    img:'https://images.unsplash.com/photo-1570126618953-d437176e8c79?w=800&q=80',
    desc:'湄南河畔顶级商场地下一层，把全泰 77 府的水上市场与小吃搬进空调室内，怕热、怕雨、时间紧的首选。',
    time:'每天 10:00–22:00，全年空调', ico:'⛴️', transport:'BTS 金线 Charoen Nakhon，或 Sathorn 码头免费摆渡船',
    eat:'各府名小吃、船面、传统甜品一站集齐', tip:'傍晚河畔有灯光喷泉秀，逛完正好看' },
  { city:'bangkok', cat:'night', hi:false, name:'考山路夜市', en:'Khao San Road', state:'Bangkok',
    img:'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800&q=80',
    desc:'全球背包客的大本营，越夜越喧闹：路边摊、文身店、廉价啤酒、街头乐队，体验泰国式狂欢的速成地。',
    time:'傍晚到深夜，周末通宵最热闹', ico:'🚐', transport:'近大皇宫，打车/Grab 或乘船到 Phra Athit 码头',
    eat:'Pad Thai 现炒、炸蝎子（猎奇）、芒果糯米饭', tip:'人多手杂看好财物；适合年轻人小酌' },
  { city:'bangkok', cat:'local', hi:false, name:'旺朗市场', en:'Wang Lang Market', state:'Bangkok',
    img:'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80',
    desc:'湄南河西岸、紧邻诗里拉吉医院的本地小吃巷，学生与上班族的食堂，价格实在、几乎没有游客滤镜。',
    time:'约 08:00–18:00，午餐时段最旺', ico:'⛴️', transport:'从 Tha Chang 码头乘船过河即到',
    eat:'椰浆糕、烤猪肉、泰式奶茶、平价海鲜饭', tip:'可与对岸大皇宫、卧佛寺串成半日游' },
  { city:'bangkok', cat:'floating', hi:false, name:'空叻玛荣水上市场', en:'Khlong Lat Mayom', state:'Bangkok 近郊',
    img:'https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=800&q=80',
    desc:'曼谷市区西侧的本地水上市场，没有游客喧嚣，运河边的炭烤、船面与现做泰式甜点便宜又地道，半天就能往返。',
    time:'周六·日 08:00–17:00', ico:'🚐', transport:'曼谷西郊 Taling Chan 区，打车约 30–40 分钟',
    eat:'炭锅海鲜、船面、椰子糕、烤河虾', tip:'可与邻近 Taling Chan 水上市场一并打卡' },
  { city:'bangkok', cat:'weekend', hi:false, name:'Don Wai 河岸市集', en:'Don Wai Market', state:'Nakhon Pathom',
    img:'https://images.unsplash.com/photo-1574484284002-952d92456975?w=800&q=80',
    desc:'曼谷近郊佛统府的老牌河岸市集，以卤鸭、河鲜与传统糕点闻名，可坐游船沿 Tha Chin 河边吃边游。',
    time:'每天约 06:00–18:00，周末最旺', ico:'🚐', transport:'曼谷西郊约 1h，自驾/包车前往',
    eat:'五香卤鸭、九层糕、河虾', tip:'游客少、价格本地，适合想避开人潮的人' },

  // ===== 清迈 CHIANG MAI =====
  { city:'chiangmai', cat:'walking', hi:true, name:'周日步行街夜市', en:'Sunday Walking Street', state:'Chiang Mai',
    img:'https://images.unsplash.com/photo-1512553353614-82a7370096dc?w=800&q=80',
    desc:'清迈最负盛名的市集，从塔佩门一路延伸进古城，整条主街被手工艺、银饰、文创和街头表演填满，氛围满分。',
    time:'仅周日 16:00–22:00', ico:'🚶', transport:'古城内 Tha Phae Gate → Ratchadamnoen Rd 主轴',
    eat:'寺庙院内美食区、Khao Soi 咖喱面、芒果冰沙', tip:'18:00 国歌响起全场起立，入乡随俗' },
  { city:'chiangmai', cat:'creative', hi:true, name:'简哈艺术市集', en:'Jing Jai Market', state:'Chiang Mai',
    img:'https://images.unsplash.com/photo-1467453678174-768ec283a940?w=800&q=80',
    desc:'清迈文艺青年的周末据点，绿树下的有机农夫市集 + 手作设计摊，咖啡香、live music 与精致甜点交织，超出片。',
    time:'周六·日 06:30–13:00（早市，越早越凉）', ico:'🚐', transport:'古城东北外，打车/Grab 约 10 分钟',
    eat:'手冲精品咖啡、有机早餐、自制酸奶与果酱', tip:'主打设计与农产，是淘伴手礼的好地方' },
  { city:'chiangmai', cat:'walking', hi:false, name:'周六步行街', en:'Saturday Walking Street · Wualai', state:'Chiang Mai',
    img:'https://images.unsplash.com/photo-1528181304800-259b08848526?w=800&q=80',
    desc:'古城南门外 Wualai 银匠街上的周六夜市，比周日街更紧凑本地，以银器手作和小吃见长，人潮稍缓。',
    time:'仅周六 16:00–22:00', ico:'🚶', transport:'古城南 Chiang Mai Gate 外 Wualai Rd',
    eat:'炭烤香肠 Sai Ua、糯米点心、现榨甘蔗汁', tip:'想买银饰，这条街源头价更实在' },
  { city:'chiangmai', cat:'night', hi:false, name:'长康夜市 / 清迈夜市', en:'Chiang Mai Night Bazaar', state:'Chiang Mai',
    img:'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&q=80',
    desc:'每天都开的老牌夜市，购物、按摩、餐酒一条龙，旁边阿努善夜市的海鲜大排档与人妖秀是经典固定节目。',
    time:'每天约 18:00–24:00', ico:'🚶', transport:'古城东外 Chang Klan Rd，沿街分布',
    eat:'阿努善海鲜烧烤、咖喱面、热带果汁', tip:'游客向、价偏高，买东西务必还价' },
  { city:'chiangmai', cat:'local', hi:false, name:'瓦洛洛市场', en:'Warorot Market', state:'Chiang Mai',
    img:'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&q=80',
    desc:'清迈最大的本地老市场，华人色彩浓厚，从泰北香肠、辣酱、干货到鲜花区一应俱全，是体验当地生活的窗口。',
    time:'每天约 06:00–17:00，清晨最鲜活', ico:'🚶', transport:'古城东北、近 Ping 河，靠近华人区',
    eat:'泰北香肠 Sai Ua、辣猪皮 Nam Prik、炸猪皮', tip:'买真空包装香肠当伴手礼，价格最实在' },

  // ===== 普吉 PHUKET =====
  { city:'phuket', cat:'walking', hi:true, name:'普吉老城周日步行街', en:'Lard Yai · Sunday Walking Street', state:'Phuket',
    img:'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=800&q=80',
    desc:'沿着 Thalang 路五彩中葡骑楼一路摆开的周日市集，老建筑、复古灯笼、街头乐手与小吃共同营造老城专属浪漫。',
    time:'仅周日 16:00–22:00', ico:'🚶', transport:'普吉老城 Thalang Road 一带',
    eat:'福建面 Hokkien Mee、月亮虾饼、Apom 椰子煎饼', tip:'白天先逛中葡骑楼与彩绘墙，傍晚接市集' },
  { city:'phuket', cat:'weekend', hi:false, name:'那卡周末夜市', en:'Naka Weekend Market', state:'Phuket',
    img:'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80',
    desc:'普吉镇规模最大的周末夜市，本地人采买与游客淘货都在这，服饰、二手货、小吃量大价廉，本地气息浓。',
    time:'周六·日 16:00–22:00 左右', ico:'🚐', transport:'普吉镇近 Central Festival 商场，打车前往',
    eat:'烤海鲜、泰式炸鸡、椰子冰沙', tip:'傍晚去最凉，雨季注意带伞' },
  { city:'phuket', cat:'local', hi:false, name:'班赞鲜市', en:'Banzaan Fresh Market', state:'Phuket · Patong',
    img:'https://images.unsplash.com/photo-1574484284002-952d92456975?w=800&q=80',
    desc:'巴东海滩旁的现代化鲜市，一楼挑生猛海鲜，楼上餐厅代加工——龙虾、老虎虾现挑现做，是吃海鲜最透明的玩法。',
    time:'每天约 07:00–22:00', ico:'🚶', transport:'巴东 Jungceylon 商场后方',
    eat:'清蒸/炭烤海鲜、咖喱蟹、冬阴功', tip:'海鲜按重量称价，先确认单价与加工费' },

  // ===== 华欣 HUA HIN =====
  { city:'huahin', cat:'creative', hi:true, name:'蝉鸣创意市集', en:'Cicada Market', state:'Hua Hin',
    img:'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80',
    desc:'华欣最有调性的艺术市集，原创设计、手作、画廊与露天舞台 live music 融为一体，傍晚草坪上的氛围像一场小型音乐节。',
    time:'周五·六·日 16:00–23:00', ico:'🚐', transport:'华欣市区南 Khao Takiab 方向，打车前往',
    eat:'美食区精致小吃、调酒、现场烧烤', tip:'旁边 Tamarind Market 美食更密集，可串逛' },
  { city:'huahin', cat:'night', hi:false, name:'华欣夜市', en:'Hua Hin Night Market', state:'Hua Hin',
    img:'https://images.unsplash.com/photo-1601314167099-232775b3d6d3?w=800&q=80',
    desc:'华欣市中心的老牌夜市，海鲜大排档冒着炭火香气，烤龙虾、咖喱蟹现点现做，兼有手信、衣饰一条街。',
    time:'每天约 18:00–24:00', ico:'🚶', transport:'市中心 Dechanuchit Rd，火车站附近',
    eat:'炭烤海鲜、咖喱蟹、芒果糯米饭', tip:'海鲜先看价目表，避免结账踩坑' },
  { city:'huahin', cat:'creative', hi:false, name:'酸豆创意市集', en:'Tamarind Market', state:'Hua Hin',
    img:'https://images.unsplash.com/photo-1467453678174-768ec283a940?w=800&q=80',
    desc:'与蝉鸣市集相邻、主打美食的夜市，棚下灯串温馨，海鲜、烧烤、甜点摊密集，可与隔壁的手作市集一并逛。',
    time:'周四–周日傍晚至深夜', ico:'🚐', transport:'华欣南、Cicada 市集旁，步行即达',
    eat:'炭烤海鲜、泰北小吃、手作甜品', tip:'先在这吃饱，再去蝉鸣听 live、逛设计' },

  // ===== 芭提雅 PATTAYA =====
  { city:'pattaya', cat:'night', hi:false, name:'泰普拉西夜市', en:'Thepprasit Night Market', state:'Pattaya',
    img:'https://images.unsplash.com/photo-1581873372796-635b67ca2008?w=800&q=80',
    desc:'芭提雅规模最大的周末夜市，服饰、小吃、海鲜与百货摊延绵一大片，价格亲民，是当地人和游客采买的首选。',
    time:'周五·六·日 17:00–23:00 为主', ico:'🚐', transport:'芭提雅南 Thepprasit Rd，双条车/Grab 可达',
    eat:'海鲜烧烤、泰式炒河粉、椰子冰淇淋', tip:'周末才是完整版，平日规模缩水' },
  { city:'pattaya', cat:'floating', hi:false, name:'四方水上市场', en:'Pattaya Floating Market', state:'Pattaya',
    img:'https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=800&q=80',
    desc:'按泰国东南西北四方风格打造的人工水上市场，木栈道、长尾船与传统表演齐备，适合时间有限、想一次看齐的游客。',
    time:'每天约 09:00–20:00，需购门票', ico:'🚐', transport:'芭提雅东南郊，打车/Grab 约 15 分钟',
    eat:'船上小吃、椰子糕、泰式甜品', tip:'偏主题乐园式，求原汁原味建议去安帕瓦' },

  // ===== 大城 AYUTTHAYA =====
  { city:'ayutthaya', cat:'floating', hi:false, name:'大城水上市场', en:'Ayothaya Floating Market', state:'Ayutthaya',
    img:'https://images.unsplash.com/photo-1528181304800-259b08848526?w=800&q=80',
    desc:'古都大城的人工水上市场，木屋水道间穿插传统歌舞与手作，逛完正好串联周边的世界遗产古寺群。',
    time:'每天约 09:00–20:00', ico:'🚆', transport:'曼谷乘火车约 1.5h 到大城，再打车',
    eat:'船面、烤大头虾、椰浆甜品', tip:'与大城古迹一日游搭配最高效' },
];

// 各城市主题路线（可选；没有的城市不显示该板块）
const CITY_ROUTES = {
  bangkok: [
    { icon:'🛺', title:'曼谷夜市三连击', dur:'1 晚', route:'乔德夜市（火山排骨）→ 席娜卡琳火车夜市（天台俯拍）→ 耀华力唐人街（深夜扫街）', why:'把曼谷三种夜市气质一次走遍：网红、复古、市井。' },
    { icon:'🚂', title:'水上 × 铁道一日游', dur:'1 天 · 经典', route:'清晨丹嫩沙朵 → 美功铁道市场看收伞 → 傍晚安帕瓦坐船看萤火虫', why:'泰国最出片的三大奇观市场，一天串成完美闭环。' },
    { icon:'🧑‍🌾', title:'湄南河西岸本地半日', dur:'半天', route:'旺朗市场（午餐）→ 空叻玛荣水上市场 → Don Wai 河岸市集', why:'没有游客滤镜，价格地道，体验真实的曼谷生活。' },
  ],
  chiangmai: [
    { icon:'🎨', title:'清迈周末市集马拉松', dur:'周六–日', route:'周六 Wualai 步行街 → 周日早简哈艺术市集 → 周日晚塔佩步行街', why:'一个周末把清迈最有调性的三个市集全部拿下。' },
    { icon:'🍜', title:'本地味觉之旅', dur:'半天', route:'瓦洛洛市场（买香肠）→ 长康/阿努善夜市（海鲜大排档）', why:'从清晨菜场到夜市烧烤，吃透泰北风味。' },
  ],
  huahin: [
    { icon:'🌅', title:'华欣创意之夜', dur:'1 晚', route:'酸豆市集吃饱 → 蝉鸣创意市集听 live、逛设计 → 海边散步', why:'海风、音乐、原创设计——华欣最文艺的打开方式。' },
  ],
};
